on:
  workflow_dispatch:
  pull_request:
    types: [ opened, reopened ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: "3.10"

    - name: Install python packages
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Prepare Selenium
      uses: nanasess/setup-chromedriver@master
      
    - name: Start XVFB
      run: |
        sudo Xvfb -ac :99 -screen 0 1920x1080x24 > /dev/null 2>&1 & # optional, disables headless mode
 
    - name: Run tests
      run: python3 -m pytest -sv
      env:
        DISPLAY: :99
